name: Test, Build and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  fe-build-test:
    runs-on: ubuntu-latest

    strategy:
     matrix:
      node-version: [16.x]

    steps:
     - uses: actions/checkout@v2
     - name: Testing Build pre-Deploy
       uses: actions/setup-node@v2
       with: 
        node-version: ${{ matrix.node-version}}
        cache: "npm"
     - run: npm i
     - run: npm run build
    deploy: 
     needs: test-build
     runs-on: ubuntu-latest

     strategy:
      matrix:
       node-version [16.x]

     steps: 
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.PORT }}
         script: |
          eval "$(ssh-agent-s)"
          ssh-add ~/.ssh/ssh-praktikan42
          echo "Cek folder project";
          [ ! -d "${HOME}/senpro/456841/modul02/senpro-github-action/" ] &&
           { 
             echo "Repostitory belum di-clone. Cloning...";
             mkdir -p ~/senpro/456841/modul02;
             cs ~/senpro/456841/modul02;
             git clone https://github.com/FreddyT2252/senpro-github-action.git;
             cd ~/senpro/456841/modul02/senpro-github-action;
             echo "Install Package and Build Project";
             nmp install;
             npm run build;
            }||
            {
             echo "Repository sudah ada. Building..."
             cd ~/senpro/456841/modul02/senpro-github-action;
             git restore .;
             git pull origin main;
             echo "Install Package dan Build Project";
             npm install;
             npm run build;
            }